NAME = $(shell basename $(shell pwd))
TITLE = Container-Kernel (Palm Pre/Pre+)
DESCRIPTION = Kernel build tree for container related experiments<br>\
<b>Note that usage of this package is very likely to void your warranty if things go wrong.<b><br>${KERNEL_DISCLAIMER}
CATEGORY = Experimental
VERSIONS = 1.4.1-6
SCREENSHOTS = 

HOMEPAGE = http://wdtz.org/cs523/
#SRC_GIT = git://git.webos-internals.org/kernels/patches.git

include ../../support/kernel.mk
